export const SET_REVIEW = 'SET_REVIEW';
export const SET_UNAPPROVED_REVIEWS = 'SET_UNAPPROVED_REVIEWS';
export const REMOVE_REVIEW = 'REMOVE_REVIEW';
export const CONSTRUCT_REVIEW = 'CONSTRUCT_REVIEW';
