export const SET_ENTITIES = 'SET_ENTITIES';

export const PURCHASE_ADD_SEAT = 'PURCHASE_ADD_SEAT';
export const PURCHASE_REMOVE_SEAT = 'PURCHASE_REMOVE_SEAT';
export const PURCHASE_SET_PERFORMANCE_ID = 'PURCHASE_SET_PERFORMANCE_ID';
