export const SET_MOVIES_PROPERTY = 'SET_MOVIE_PROPERTY';
export const SET_ENTITIES = 'SET_ENTITIES';
export const UPDATE_ENTITY = 'UPDATE_ENTITY';
export const UPDATE_NEW_MOVIE = 'UPDATE_NEW_MOVIE';
export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
