export const ADD_QUESTION = 'survey/ADD_QUESTION';
export const REMOVE_QUESTION = 'survey/REMOVE_QUESTION';
export const SET_INITIAL_STATE = 'survey/SET_INITIAL_STATE';
export const SET_PROPERTY = 'survey/SET_PROPERTY';
export const SET_ENTITIES = 'SET_ENTITIES';
export const UPDATE_ENTITY = 'UPDATE_ENTITY';
export const TOGGLE_QUESTION_REQUIRED = 'TOGGLE_QUESTION_REQUIRED';
