export const PURCHASE_ADD_SEAT = 'PURCHASE_ADD_SEAT';
export const PURCHASE_REMOVE_SEAT = 'PURCHASE_REMOVE_SEAT';
export const PURCHASE_SET_PERFORMANCE_ID = 'PURCHASE_SET_PERFORMANCE_ID';
export const SET_SEAT_TAKEN = 'SET_SEAT_TAKEN';
export const EMPTY_SEATS = 'EMPTY_SEATS';
export const SET_TICKET_DISCOUNT = 'SET_TICKET_DISCOUNT';
export const SET_CALCULATED_DISCOUNT = 'SET_CALCULATED_DISCOUNT';
export const SET_PURCHASE_PROPERTY = 'SET_PURCHASE_PROPERTY';
